banks:
  icbc: '工商银行'
  abc: '农业银行'
  ccb: '建设银行'
  bcm: '交通银行'
  boc: '中国银行'
  cmb: '招商银行'
  bob: '北京银行'
  dlcb: '大连银行'
  cgb: '广发银行'
  gzcb: '广州银行'
  hxb: '华夏银行'
  jlbk: '吉林银行'
  spdb: '浦发银行'
  bosh: '上海银行'
  pab: '平安银行'
  sjbc: '盛京银行'
  cib: '兴业银行'
  czb: '浙商银行'
  ceb: '光大银行'
  cmbc: '民生银行'
  psbc: '中国邮储'
  cncb: '中信银行'
