pricing:
  strategy_one:
    base:
      '_traffic': 10
    items:
      'electronic/lighting': 30
      'electronic/socket': 20
      'electronic/appliance': 80
      'electronic/other': 50
      'water/pipe': 30
      'water/faucet': 30
      'water/toilet': 50
      'water/other': 50
      'misc/shelf': 20
      'misc/air_conditioning': 80
      'misc/whitewash': 50
      'misc/lock': 60
      'misc/other': 60
    cities:
      - 431000
      - 430100
