taxons:
  categories:
    - electronic
    - water
    - misc
  items:
    electronic:
      - lighting
      - socket
      - appliance
      - other
    water:
      - pipe
      - faucet
      - toilet
      - other
    misc:
      - shelf
      - air_conditioning
      - whitewash
      - lock
      - other
  certified_status:
    success: success
    fail: fail
    under_review: under_review
  reason_code:
    - missing_info
    - out_of_date


